### ISSUE TITLE
select event not fired for autcomplete using keyboard enter

### ISSUE THREAD

**Issue by sumitd** [aehlke/tag-it#163]
Select event is not getting fired when using keyboard ENTER, but only work when selecting item with mouse. Any work around to get the select event fired when selecting with keyboard.

$("#myTags").tagit({
      availableTags: ["c++", "java", "php", "javascript", "ruby", "python", "c"],
      autocomplete: {
            select: function(event, ui) {
                alert('select fired');
            }
       }
});

**Comment by nrsarath** [comment]
This issue cannot be reffered to #164. Please provide a solution to select the values using keyboard

**Comment by yuyongyu08** [comment]
I have same problem,Please provide a solution!!!!
