### ISSUE TITLE
only last tag is transfered via POST

### ISSUE THREAD

**Issue by ghost** [aehlke/tag-it#263]
hi guys,

little issue:

I have implemented tag-it and it's working well from the ui-perspective but when it comes to transfering the tags via POST only the last entered tag is available. the var_dump in PHP says the following:

 ["tags"]=> string(4) "tag2"

and of course there is also a "tag1" but it's not transfered!

Does somebody else have this issue?

**Comment by fanux365** [comment]
https://github.com/aehlke/tag-it/issues/235
