### ISSUE TITLE
Is there a way to just show the tags outside of input?

### ISSUE THREAD

**Issue by danboh** [aehlke/tag-it#367]
First of all, thanks a lot for this. Excellent work!

Now, I'm wondering how I could display the tags in a way that there's no input, and the user won't be adding any more tags. I would like to display the tags with the same style they have when they're entered in the input field.

Any thoughts?

Thanks!

**Comment by sabbiseaan** [comment]
then why dont you just dispaly:none your input box.or . tagit .tagit-new { opacity:0}
