### ISSUE TITLE
Documentation: jQuery UI dependencies

### ISSUE THREAD

**Issue by nemesifier** [aehlke/tag-it#61]
Which are the jQuery UI dependencies of tag-it? It would be nice to write it somewhere.

**Comment by gavinkilbride** [comment]
Autocomplete has a dependency on Menu so the full list of JQuery UI Dependencies are:

* Core
* Widget
* Position
* Autocomplete
* **Menu**
* Effects Core
* Effect "Blind"

**Comment by aehlke** [comment]
PR welcome ^ :)
